[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"

[lib]
name = "lib"
path = "src/lib/mod.rs"

[[bin]]
name = "2023-01"
path = "src/bin/2023/01/main.rs"
